on:
  push:
    branches:
      - main
name: LaravelApp
jobs:
  web-deploy:
    name: 🎉 EZOOM DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files - FRONTEND
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_EZOOM }}
          password: ${{ secrets.FTP_PASSWORD_EZOOM }}
          local-dir: ./public/
          server-dir: ./ezoomdev/
          exclude: |
            - index.php

      - name: 📂 Sync files - BACKEND
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username_ezoom }}
          password: ${{ secrets.ftp_password_ezoom }}
          server-dir: ../apps/ezoomdev/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.idea/**
            **/tests/**
            **/public/**
            **/docker/**
            **/stubs/**
            **/*/debugbar/
            **/*/logs/.log*
            **/*/framework/cache/
